### ISSUE TITLE
Problems with your Python files

### ISSUE THREAD

**Issue by SnivySquid65** [xtream1101/MinecraftArchive#5]
Hey there @xtream1101!  I just downloaded python and ran the files that you wanted, but my pc doesn't pull up anything.  So how do I run it?  If python can't run either one, how am I supposed to run it?  I would appreciate it if you answer my question.

Thank you,
-SnivySquid65

**Comment by xtream1101** [comment]
Its very possible that this no longer works as it was made back in 2016.

**Comment by SnivySquid65** [comment]
Ok then, I did find another way to do what I wanted but thank you for putting your efforts into this!
-SnivySquid65
